name = "SimpleAlgebra"
uuid = "c653966b-d9be-4146-a61d-9a13ffa1fe75"
version = "0.1.0"
authors = ["ferreol <ferreol.soulez@univ-lyon1.fr>"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonuniformFFTs = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
SimpleAlgebraCUDAExt = ["CUDA"]
SimpleAlgebraFluxExt = ["CUDA", "Flux"]
SimpleAlgebraLinearAlgebraExt = ["LinearAlgebra"]
SimpleAlgebraNonuniformFFTsExt = ["NonuniformFFTs"]
SimpleAlgebraUnitfulExt = ["Unitful"]
SimpleAlgebraZygoteExt = ["Zygote"]

[compat]
AbstractFFTs = "1"
Adapt = "3, 4"
ArrayTools = "0.3"
CUDA = "4, 5"
ChainRulesCore = "1"
FFTW = "1"
Flux = "0.16"
Functors = "0.5"
InverseFunctions = "0.1.10"
KernelAbstractions = "0.9"
NonuniformFFTs = "0.8"
StaticArrays = "1"
Unitful = "1"
Zygote = "0.6, 0.7"
julia = "1.10"
